// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// choosecpp
uint64_t choosecpp(uint64_t n, uint64_t k);
RcppExport SEXP _testingtravis_choosecpp(SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< uint64_t >::type n(nSEXP);
    Rcpp::traits::input_parameter< uint64_t >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(choosecpp(n, k));
    return rcpp_result_gen;
END_RCPP
}
// comb_index
Rcpp::IntegerMatrix comb_index(int n_units, int comb);
RcppExport SEXP _testingtravis_comb_index(SEXP n_unitsSEXP, SEXP combSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_units(n_unitsSEXP);
    Rcpp::traits::input_parameter< int >::type comb(combSEXP);
    rcpp_result_gen = Rcpp::wrap(comb_index(n_units, comb));
    return rcpp_result_gen;
END_RCPP
}
// comb_names
Rcpp::CharacterVector comb_names(CharacterVector elements, int comb);
RcppExport SEXP _testingtravis_comb_names(SEXP elementsSEXP, SEXP combSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type elements(elementsSEXP);
    Rcpp::traits::input_parameter< int >::type comb(combSEXP);
    rcpp_result_gen = Rcpp::wrap(comb_names(elements, comb));
    return rcpp_result_gen;
END_RCPP
}
// mat2list
Rcpp::List mat2list(NumericMatrix inmat);
RcppExport SEXP _testingtravis_mat2list(SEXP inmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type inmat(inmatSEXP);
    rcpp_result_gen = Rcpp::wrap(mat2list(inmat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_testingtravis_choosecpp", (DL_FUNC) &_testingtravis_choosecpp, 2},
    {"_testingtravis_comb_index", (DL_FUNC) &_testingtravis_comb_index, 2},
    {"_testingtravis_comb_names", (DL_FUNC) &_testingtravis_comb_names, 2},
    {"_testingtravis_mat2list", (DL_FUNC) &_testingtravis_mat2list, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_testingtravis(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
