// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// shuffle_rowwise
arma::umat shuffle_rowwise(arma::umat inmat);
RcppExport SEXP _testingtravis_shuffle_rowwise(SEXP inmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::umat >::type inmat(inmatSEXP);
    rcpp_result_gen = Rcpp::wrap(shuffle_rowwise(inmat));
    return rcpp_result_gen;
END_RCPP
}
// shuffle_checkerboard
arma::umat shuffle_checkerboard(IntegerMatrix inmat, int swaps, bool checkerboards_only);
RcppExport SEXP _testingtravis_shuffle_checkerboard(SEXP inmatSEXP, SEXP swapsSEXP, SEXP checkerboards_onlySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type inmat(inmatSEXP);
    Rcpp::traits::input_parameter< int >::type swaps(swapsSEXP);
    Rcpp::traits::input_parameter< bool >::type checkerboards_only(checkerboards_onlySEXP);
    rcpp_result_gen = Rcpp::wrap(shuffle_checkerboard(inmat, swaps, checkerboards_only));
    return rcpp_result_gen;
END_RCPP
}
// sri_mat
arma::mat sri_mat(IntegerMatrix inmat);
RcppExport SEXP _testingtravis_sri_mat(SEXP inmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type inmat(inmatSEXP);
    rcpp_result_gen = Rcpp::wrap(sri_mat(inmat));
    return rcpp_result_gen;
END_RCPP
}
// choosecpp
uint64_t choosecpp(uint64_t n, uint64_t k);
RcppExport SEXP _testingtravis_choosecpp(SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< uint64_t >::type n(nSEXP);
    Rcpp::traits::input_parameter< uint64_t >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(choosecpp(n, k));
    return rcpp_result_gen;
END_RCPP
}
// comb_index
Rcpp::IntegerMatrix comb_index(int n_units, int comb);
RcppExport SEXP _testingtravis_comb_index(SEXP n_unitsSEXP, SEXP combSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_units(n_unitsSEXP);
    Rcpp::traits::input_parameter< int >::type comb(combSEXP);
    rcpp_result_gen = Rcpp::wrap(comb_index(n_units, comb));
    return rcpp_result_gen;
END_RCPP
}
// comb_names
Rcpp::CharacterVector comb_names(CharacterVector elements, int comb);
RcppExport SEXP _testingtravis_comb_names(SEXP elementsSEXP, SEXP combSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type elements(elementsSEXP);
    Rcpp::traits::input_parameter< int >::type comb(combSEXP);
    rcpp_result_gen = Rcpp::wrap(comb_names(elements, comb));
    return rcpp_result_gen;
END_RCPP
}
// mat2list
Rcpp::List mat2list(NumericMatrix inmat);
RcppExport SEXP _testingtravis_mat2list(SEXP inmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type inmat(inmatSEXP);
    rcpp_result_gen = Rcpp::wrap(mat2list(inmat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_testingtravis_shuffle_rowwise", (DL_FUNC) &_testingtravis_shuffle_rowwise, 1},
    {"_testingtravis_shuffle_checkerboard", (DL_FUNC) &_testingtravis_shuffle_checkerboard, 3},
    {"_testingtravis_sri_mat", (DL_FUNC) &_testingtravis_sri_mat, 1},
    {"_testingtravis_choosecpp", (DL_FUNC) &_testingtravis_choosecpp, 2},
    {"_testingtravis_comb_index", (DL_FUNC) &_testingtravis_comb_index, 2},
    {"_testingtravis_comb_names", (DL_FUNC) &_testingtravis_comb_names, 2},
    {"_testingtravis_mat2list", (DL_FUNC) &_testingtravis_mat2list, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_testingtravis(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
