# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

choosecpp <- function(n, k) {
    .Call(`_testingtravis_choosecpp`, n, k)
}

comb_index <- function(n_units, comb) {
    .Call(`_testingtravis_comb_index`, n_units, comb)
}

comb_names <- function(elements, comb) {
    .Call(`_testingtravis_comb_names`, elements, comb)
}

#' Turn matrix into list
#'
#' @param inmat numeric or integer matrix, 0/1 matrix. Must have column names!
#' @return a list where each item represents a row in \code{inmat} and is a
#'         character vector with the column names for which a row value is 1
#' @details The function will fail if the input matrix does not have column
#'          names or if it is a not a \code{matrix}, but for example a
#'          \code{data.frame}.
#' @author Christof Neumann
#' @export
mat2list <- function(inmat) {
    .Call(`_testingtravis_mat2list`, inmat)
}

